image: docker:latest

services:
    - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  
stages:
  - build
  - deploy

build-latest:
  stage: build
  script:
    - docker build --build-arg TICKET_ID=$TICKET_ID --pull -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME -f Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

# deploy:
#   stage: deploy
#   environment: $CI_BUILD_REF_NAME
#   stage: deploy
#   image: cdrx/rancher-gitlab-deploy
#   script:
#     - upgrade --rancher-url $RANCHER_URL --rancher-key $RANCHER_KEY --rancher-secret $RANCHER_SECRET --stack $CI_BUILD_REF_NAME --service one-hour-one-life --environment theraccoonbear
